{
 "title": "Transcendance Healthchecks Dashboard",
 "tags": [
  "transcendance",
  "healthcheck"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🏥 Services Health Status",
   "type": "table",
   "description": "État des healthchecks de tous les services Transcendance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"transcendance-healthchecks\"}"
    }
   ]
  },
  {
   "title": "📊 Services Overview",
   "type": "piechart",
   "description": "Nombre total de services UP vs DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"transcendance-healthchecks\"})",
     "legendFormat": "Services UP"
    },
    {
     "expr": "sum(1 - probe_success{job=\"transcendance-healthchecks\"})",
     "legendFormat": "Services DOWN"
    }
   ]
  },
  {
   "title": "👥 Online Users",
   "type": "stat",
   "description": "Nombre d'utilisateurs actuellement en ligne",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendance_online_users_nbuser"
    }
   ]
  },
  {
   "title": "📈 Online Users Trend",
   "type": "timeseries",
   "description": "Évolution du nombre d'utilisateurs en ligne dans le temps",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "transcendance_online_users_nbuser"
    }
   ]
  },
  {
   "title": "👥 Online Game",
   "type": "stat",
   "description": "Nombre de partie actuellement en ligne",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendance_online_party_count"
    }
   ]
  },
  {
   "title": "📈 Online Game Trend",
   "type": "timeseries",
   "description": "Évolution du nombre de partie dans le temps",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "transcendance_online_party_count"
    }
   ]
  }
 ]
}