global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'grafana'
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'grafana:4242'

- job_name: 'blackbox'
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'blackbox-exporter:9115'

- job_name: 'transcendance-healthchecks'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - https://game:3002/health
    - https://gate:3005/health
    - https://public:3000/health
    - https://user:3001/health
    - https://ia:3003/health
    - http://kibana:5601/kibana/api/status
    - http://logstash:9600/_node/stats
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115

- job_name: 'transcendance-online-users'
  metrics_path: /probe
  params:
    module: [default]
  static_configs:
  - targets:
    - 'https://gate:3005/user/nb_online'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: json-exporter:7979

- job_name: 'transcendance-game'
  metrics_path: /probe
  params:
    module: [default]
  static_configs:
  - targets:
    - 'https://gate:3005/game/monitoring'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: json-exporter:7979